name: forLaba4
on:
  push:
    branches: [ Lab4 ]
  pull_request:
    branches: [ Lab4 ]
jobs: 
  task1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: install valgrind and splint
      run: |
            sudo apt install valgrind
            sudo apt install splint
    - name: compiling and test
      run: |
            cd 4laba1ind
            make 
            cd ..
              
    - name: check code with valgrind
      run: |
            cd 4laba1ind
            echo "G(new)reat(h)aa" > i.txt
            valgrind ./program < i.txt 
    - name: check code with slint
      run: |
            cd 4laba1ind
            splint  -predboolothers -retvalother -exportlocal -boolops 4_1.c
  task2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: install valgrind and splint
      run: |
            sudo apt install valgrind
            sudo apt install splint
    - name: compiling and test
      run: |
            cd 4laba2ind
            make 
            cd ..
              
    - name: check code with valgrind
      run: |
            cd 4laba2ind
            valgrind ./program 
    - name: check code with slint
      run: |
            cd 4laba2ind
            splint   -predboolothers -retvalother -exportlocal -boolops -retvalint -nullpass  +matchanyintegral 4_2.c
  task3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: install valgrind and splint
      run: |
            sudo apt install valgrind
            sudo apt install splint
    - name: compiling and test
      run: |
            cd 5laba
            make 
            cd ..
              
    - name: check code with slint
      run: |
            cd 5laba
            splint
